# Generated by Django 3.2.6 on 2022-02-18 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Er',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Er_Brand', models.CharField(max_length=20)),
                ('Er_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Er_Num', models.CharField(blank=True, max_length=20, null=True)),
                ('ErAd_Add', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Th_Name', models.CharField(max_length=20)),
                ('Th_Genre', models.CharField(max_length=20)),
                ('Th_Diff', models.CharField(blank=True, max_length=10, null=True)),
                ('Th_Fear', models.CharField(blank=True, max_length=10, null=True)),
                ('Th_Act', models.CharField(blank=True, max_length=10, null=True)),
                ('Th_Intro', models.TextField(blank=True, max_length=500, null=True)),
                ('Th_Img1', models.ImageField(blank=True, default='/image/noimage.png', null=True, upload_to='image/th/')),
                ('Th_Img2', models.ImageField(blank=True, default='/image/noimage.png', null=True, upload_to='image/th/')),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.er')),
            ],
        ),
        migrations.CreateModel(
            name='ThGr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThGr_Pt', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ThGr_Review', models.TextField(blank=True, max_length=200, null=True)),
                ('th', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='keys.th')),
            ],
        ),
    ]
