# Generated by Django 3.2.6 on 2022-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20220313_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th',
            name='Th_Genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='th',
            name='Th_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
