# Generated by Django 3.2.6 on 2021-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_CODE', models.CharField(max_length=8)),
                ('ID', models.CharField(max_length=8)),
                ('PW', models.CharField(max_length=8)),
                ('EMAIL', models.EmailField(max_length=8)),
                ('Phone_Number1', models.CharField(max_length=8)),
                ('Phone_Number2', models.CharField(max_length=8)),
                ('Phone_Number3', models.CharField(max_length=8)),
                ('Birth_Year', models.CharField(max_length=8)),
                ('Birth_Month', models.CharField(max_length=8)),
                ('Birth_Day', models.CharField(max_length=8)),
            ],
        ),
    ]
