# Generated by Django 3.2.6 on 2021-12-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0002_fc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='er',
            name='Er_Grpt',
        ),
        migrations.RemoveField(
            model_name='er',
            name='Er_Review',
        ),
    ]
