# Generated by Django 3.2.6 on 2021-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0003_rename_thgr_code_thgr_th_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='thgr',
            name='ThGr_CODE',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
