# Generated by Django 3.2.6 on 2021-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0004_thgr_thgr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='thimg',
            name='ThGr_CODE',
            field=models.CharField(default=11111111, max_length=8),
            preserve_default=False,
        ),
    ]
