# Generated by Django 3.2.6 on 2021-11-20 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0005_thimg_thgr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='th',
            old_name='ErTh_CODE',
            new_name='Er_CODE',
        ),
        migrations.RemoveField(
            model_name='er',
            name='ErTh_CODE',
        ),
        migrations.AlterField(
            model_name='th',
            name='Th_Act',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='th',
            name='Th_Diff',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='th',
            name='Th_Fear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='thgr',
            name='ThGr_pt',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
