# Generated by Django 3.2.6 on 2021-08-29 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Er',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Er_CODE', models.CharField(max_length=8)),
                ('ErTh_CODE', models.CharField(max_length=8)),
                ('ErAd_CODE', models.CharField(max_length=8)),
                ('Er_Name', models.CharField(max_length=20)),
                ('Er_Num', models.CharField(max_length=20)),
                ('Er_Grpt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Er_Review', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Th_CODE', models.CharField(max_length=8)),
                ('ErTh_CODE', models.CharField(max_length=8)),
                ('Th_Name', models.CharField(max_length=20)),
                ('Th_Genre', models.CharField(max_length=20)),
                ('Th_Diff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Th_Fear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Th_Act', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Th_Intro', models.TextField(max_length=200)),
                ('Th_Review', models.TextField(max_length=200)),
                ('th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.er')),
            ],
        ),
        migrations.CreateModel(
            name='ThPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThPic_CODE', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, default='/image/th/', null=True, upload_to='th')),
                ('th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='th.th')),
            ],
        ),
        migrations.CreateModel(
            name='ThGr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThGr_CODE', models.CharField(max_length=8)),
                ('ThGr_pt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ThGr_review', models.TextField(max_length=200)),
                ('th', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='th.th')),
            ],
        ),
        migrations.CreateModel(
            name='ErAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErAd_CODE', models.CharField(max_length=8)),
                ('ErAd_Num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('ErAd_Add1', models.CharField(max_length=20)),
                ('ErAd_Add2', models.CharField(max_length=20)),
                ('ErAd_Add3', models.CharField(max_length=20)),
                ('ErAd_Add4', models.CharField(max_length=20)),
                ('ErAd_Add5', models.CharField(max_length=20)),
                ('er', models.OneToOneField(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='th.er')),
            ],
        ),
    ]
