# Generated by Django 3.2.6 on 2021-08-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0002_auto_20210829_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thpic',
            old_name='image',
            new_name='Th_pic',
        ),
    ]
