# Generated by Django 3.2.6 on 2021-12-11 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Er',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Er_Name', models.CharField(max_length=20)),
                ('Er_Num', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fc_Name', models.CharField(max_length=20)),
                ('Fc_Num', models.CharField(max_length=20, null=True)),
                ('Fc_Brn', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Th_Name', models.CharField(max_length=20)),
                ('Th_Genre', models.CharField(max_length=20)),
                ('Th_Diff', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Th_Fear', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Th_Act', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Th_Intro', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.er')),
            ],
        ),
        migrations.CreateModel(
            name='ThImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Th_img', models.ImageField(blank=True, default='/image/noimage.png', null=True, upload_to='image/th/')),
                ('create_date', models.DateTimeField()),
                ('th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.th')),
            ],
        ),
        migrations.CreateModel(
            name='ThGr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThGr_pt', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ThGr_review', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('th', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='keys.th')),
            ],
        ),
        migrations.CreateModel(
            name='ErAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErAd_Num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('ErAd_Add1', models.CharField(max_length=20)),
                ('ErAd_Add2', models.CharField(max_length=20)),
                ('ErAd_Add3', models.CharField(max_length=20)),
                ('ErAd_Add4', models.CharField(max_length=20)),
                ('ErAd_Add5', models.CharField(max_length=20)),
                ('er', models.OneToOneField(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='keys.er')),
            ],
        ),
    ]
