# Generated by Django 3.2.6 on 2021-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er',
            name='ErAd_Add1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
