# Generated by Django 3.2.6 on 2021-12-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keys', '0003_auto_20211215_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThGrImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThGr_img', models.ImageField(blank=True, default='/image/noimage.png', null=True, upload_to='image/thgr/')),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.thgr')),
            ],
        ),
        migrations.CreateModel(
            name='ErImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Er_img', models.ImageField(blank=True, default='/image/noimage.png', null=True, upload_to='image/er/')),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.er')),
            ],
        ),
    ]
