# Generated by Django 3.2.6 on 2021-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_erimg_thgrimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='er',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erimg',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='th',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thgr',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thgrimg',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thimg',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
